### ISSUE TITLE
Slow CP page loading

### ISSUE THREAD

**Issue by ottz0** [aerni/statamic-font-awesome#10] opened 2022-06-14 23:35 UTC
I'm pretty sure this is related to this addon. https://github.com/statamic/cms/issues/6160.

I'm viewing collection pages in the CP and the pages are loading quite slow. I'm also using vue.js but i'm getting these console errors when i'm viewing the content pages in the CP which is probably why the pages are loading slow.

I'm not getting these errors when viewing the actual pages and I don't get these errors when viewing other collections in the CP

![](https://user-images.githubusercontent.com/7971800/172096603-c41da613-52f5-430e-81fd-320a584d2464.png)

**Comment by mbryne** [comment] 2022-06-15 04:39
I just want to chime in here.

I can’t talk to the vue.js errors but I did experience slow loading speeds on the control panel with this extension enabled.

I have just noticed this in the documentation.

> Note: If you are using a Font Awesome Kit with SVG as technology, you may run into performance issues when selecting icons. Change the technology to Web Font to speed things up.

I’ll give that a try and see if that resolves the issue.

**Comment by aerni** [comment] 2022-06-15 11:38
I can't reproduce this error. If you're experiencing performance issues, you should do what @mbryne pointed out. If that doesn't solve your problem, please reproduce the issue in a clean repo and post the link here.

**Comment by pushpanda** [comment] 2022-07-07 14:48
i can reproduce this error as i get 3mb added to the loaded statamic document size for every font_awesome field in my blueprint. i'm using fontawesome pro, v6 latest, webfont

**Comment by aerni** [comment] 2022-07-12 20:43
Feel free to PR a fix for this.

**Comment by aerni** [comment] 2023-01-28 19:55
Ok, I think I have found the cause of this. Right now, we are passing all icons as metadata to each select field. To get rid of this performance bottleneck, we have to refactor the code to fetch the icons from within the Vue fieldtype whenever they are requested. I'll try to get a fix out at some point.

**Closed as completed** 2023-02-01 23:15 UTC
Labels: bug
