### ISSUE TITLE
Argument #1 ($icon) must be of type Statamic\Fields\Value, Statamic\Fields\LabeledValue given

### ISSUE THREAD

**Issue by goellner** [aerni/statamic-font-awesome#20] opened 2023-09-25 14:45 UTC
getting this error with Statamic 4.23.1, haven't tested any other Statamic version yet.
```
Aerni\FontAwesome\FontAwesomeTags::output(): Argument #1 ($icon) must be of type Statamic\Fields\Value, Statamic\Fields\LabeledValue given, called in /Users/elektro/code/hm-website/vendor/aerni/font-awesome/src/FontAwesomeTags.php on line 16
```

Adding `Value|LabeledValue` to the output methods types fixes it

**Comment by aerni** [comment] 2023-09-25 15:41
I can't reproduce this issue. When do you get it? How can I reproduce it?

**Comment by goellner** [comment] 2023-09-25 18:00
i will try to make a repo tomorrow for you

**Comment by aerni** [comment] 2023-10-30 17:44
Is this still an open issue for you? If not, I'll close it.

**Closed as completed** 2023-11-29 14:25 UTC
